doEliteMobsLoot: true
doMMORPGColorsForItems: true
preventCustomItemPlacement: true
itemLoreStructure:
- $enchantments
- $potionEffect
- §m----------------------
- $customLore
- $itemSource
- $loreResaleValue
- 精英怪物装备
- §m----------------------
- 品质：$tier
shopSourceItemLore: 从商店购买而得
mobSourceItemLore: 从精英$mob身上掠夺而得
loreWorth: 价值$worth $currencyName
loreResaleValue: 出售可获得$resale $currencyName
flatDropRate: 0.25
tierIncreaseDropRate: 0.05
proceduralItemDropWeight: 90.0
weighedItemDropWeight: 1.0
fixedItemDropWeight: 10.0
limitedItemDropWeight: 3.0
scalableItemDropWeight: 6.0
defaultLootMultiplier: 0.0
levelCapForDefaultLootMultiplier: 200
defaultExperienceMultiplier: 1.0
maximumLootTier: 100
useEliteEnchantments: true
doRareDropsEffect: true
eliteEnchantmentLoreString: '&6精英'
useHoesAsWeapons: false
