dropProcedurallyGeneratedItems: true
customEnchantmentChance: 0.1
nameFormats:
- $noun $verb
- $verb-er $adjective
- $verb-er $adjective $verb
- $verb-er $adjective для $verb
- $itemType $verb
- $noun для $verb
- $verb-er $adjective из $verb
nouns:
- Дымка
- Борода
- Тетива
- Суть
- Амуниция
- Шпилька
- Крепость
- Хворостина
- Лапа
- Подпояска
- Мантикора
- Груда
- Клюка
- Окружность
- Жердь
- Академия
- Альбиция
- Арена
- Арка
- Архаика
- Атака
- Баллиста
- Баррикада
- Башня
- Бдительность
- Безделушка
- Безнравственность
- Бесконечность
- Битва
- Бойня
- Брешь
- Бритва
- Броня
- Бусина
- Ведьминская шляпа
- Верность
- Вершина
- Ветвь
- Вечность
- Власть
- Возвышенность
- Воинственность
- Война
- Волшебная шляпа
- Воля
- Вражда
- Вселенная
- Вспышка
- Гавань
- Гармония
- Гербовая накидка
- Гибель
- Гильза
- Глыба
- Грань
- Громада
- Дамба
- Джунглевая маска
- Диковинка
- Дикость
- Длань
- Добродетель
- Дробилка
- Дуга
- Душа
- Ель
- Жажда
- Жемчужина
- Жуткая рожа
- Завязка
- Защита
- Звезда
- Звездочка
- Злость
- Змеиная кожа
- Знатность
- Ива
- Игрушка
- Издевка
- Интрига
- Истина
- Ищущая шляпа
- Каска
- Клеть
- Клешня
- Клятва
- Когорта
- Колдовская сфера
- Колдовская шляпа
- Кольчужная броня
- Комета
- Кость
- Кромка
- Ладонь
- Ловушка
- Лоза
- Луна
- Лунная дорожка
- Лучина
- Магическая сфера
- Магическая шляпа
- Мантия
- Медитация
- Метка
- Мечта
- Мишень
- Мощь
- Мудрость
- Муза
- Награда
- Наплечная броня
- Находка
- Небесная сфера
- Неважная шляпа
- Неколебимость
- Нирвана
- Нитка бус
- Ножная броня
- Ночь
- Обманка
- Обшивка
- Оджа
- Оккультная шляпа
- Опасность
- Опора
- Орбита
- Осада
- Острота
- Острый нож
- Ость
- Отрава
- Охота
- Охотничья накидка
- Палка
- Палка для ходьбы
- Пелена
- Петля
- Пила
- Плеть
- Плотная маска
- Победа
- Побрякушка
- Погремушка
- Подмога
- Подпруга
- Полемика
- Порча
- Поступь рока
- Похвала
- Привязь
- Приманка
- Проницательность
- Прорицательская шляпа
- Пустота
- Пытка
- Разруха
- Расплата
- Распря
- Редкость
- Роскошная шляпа
- Связка
- Связь
- Святыня
- Сила
- Скорлупа
- Слава
- Смерть
- Спираль
- Стена
- Стихия
- Стойкость
- Странность
- Стрела
- Стяжка
- Судьба
- Суровость
- Сфера
- Тайна
- Тень
- Точность
- Традиция
- Тросточка
- Трость
- Тьма
- Тяжба
- Тяжелая дубина
- Тяжесть
- Угроза
- Удавка
- Уловка
- Умбра
- Услуга
- Утяжеленная дубина
- Форма
- Хватка
- Хитрость
- Храбрость
- Цепочка
- Чародейская шляпа
- Челюсть
- Черная магия
- Чернь
- Честность
- Честь
- Чешуйка
- Шапочка
- Шарада
- Шестеренка
- Шляпа разума
- Шляпа с полями
- Шляпа сторожа
- Шляпа стража
- Экипировка
- Энергетическая линия
- Энергия
adjectives:
- Яростный клинок
- Ясновидящий хлыст
- Ястребиный глаз
- Ятаган
- Принуждатель
- Ломатель
- Корсет
- Шраморез
- Душегуб
- Знак
- Герб
- Воротник
- Футляр
- Охват
- Кладезь
- Надрезатель
- Наказыватель
- Распылитель
- Крюк
- Сковыватель
- Апогей
- Сжиматель
- Скальп
- Дублет
- Плащ-обманка
- Наблюдатель
- Вредитель
- Сотрясатель
- Сук
- Доминион
- Вминатель
- Транс
- Сенешаль
- Воздаватель
- Орден
- Оберег
- Жребий
- Венок
- Высекатель
- Дар
- Порок
- Фанатизм
- Ультиматум
- Коготок
- Взыматель податей
- Мешочек
- Гребень
- Пережиток
- Адъюнкт
- Ученик
- Учитель
- Гуру
- Оградитель
- Изъян
- Магмарь
- Авангард
- Авторитет
- Адепт
- Академический жезл
- Алмаз
- Альянс
- Ангел
- Арбутус
- Аристократ
- Арканум
- Артефакт
- Аспект
- Ассасин
- Базис
- Бандаж
- Барон
- Бастион
- Батальон
- Бич
- Благодетель
- Блеск
- Боец
- Божественный удар
- Брадобрей
- Бронированный шлем
- Брусок
- Вал
- Валун
- Ведьминский жезл
- Ведьминский талисман
- Великий молот
- Верх
- Вершитель
- Взгляд
- Височный удар
- Владыка
- Военачальник
- Военный трофей
- Волнолом
- Волшебный жезл
- Вопль
- Воспитанник
- Враг
- Высокий совет
- Выстрел
- Гадательный жезл
- Гайдук
- Гарнизон
- Генезис
- Геральд
- Геральдический щит
- Герой
- Гипноз
- Гипнотизм
- Гладиатор
- Глаз
- Глупец
- Головорез
- Горизонт
- Горн
- Грохот
- Гурт
- Дежурный
- Дикарь
- Дипломат
- Доверенный
- Дозор
- Дозорный
- Долг
- Дониматель
- Дуб
- Дух
- Духопризыватель
- Дуэлянт
- Жгут
- Завет
- Завоеватель
- Заговорённый жезл
- Закал
- Заклинательный жезл
- Замах
- Замок
- Заряд
- Заслон
- Захват
- Защитный шлем
- Злоумышленник
- Избиватель
- Изгиб
- Искатель
- Иссекатель
- Источник
- Истребитель
- Камень
- Камешек
- Камнетес
- Капкан
- Каркас
- Кивер
- Кипарис
- Клин
- Клинок
- Кокон
- Колодец
- Колпак
- Командирский шлем
- Короб
- Костеруб
- Кошмар
- Крест
- Кристалл
- Круг
- Крупный амулет
- Крушитель
- Кулак
- Кулон
- Купол
- Ларец
- Латный шлем
- Легион
- Легионер
- Лесной житель
- Ловец
- Луч
- Магический жезл
- Магнус
- Маниту
- Мародер
- Маршрут
- Маскировочный костюм
- Мастер
- Мастерский жезл
- Меридиан
- Металл
- Меткий стрелок
- Мим
- Мир
- Мирмидон
- Мистический посох
- Могильщик
- Могучий кулак
- Молот
- Молоток
- Монах
- Мрак
- Мрачный взгляд
- Мститель
- Мундир
- Мыслитель
- Мыслительный шлем
- Мясник
- Нагрудник
- Наемник
- Накулачник
- Наплеч обороны
- Нарукавник
- Наряд
- Наставник
- Натиск
- Недруг
- Нексус
- Обелиск
- Обломок
- Ободок
- Оборонитель
- Оборот
- Образ
- Обруч
- Обсидиан
- Оккультный жезл
- Оплот
- Орел
- Осадник
- Осколок
- Отголосок
- Отложной воротник
- Отсекатель
- Офицер
- Охотник
- Паж
- Панцирь
- Первоисточник
- Перехватчик
- Пик
- Пилон
- Пинок
- Плащ
- Плащ сыщика
- Плетеный ремень
- Победитель
- Поборник
- Покой
- Покров
- Покровитель
- Полет
- Порядок
- Посланник
- Последователь
- Посмертный дар
- Почерк
- Пояс
- Поясок
- Предвестник
- Предсказатель
- Приз
- Пристальный взгляд
- Пристальный взор
- Прицел
- Проводник
- Пролом
- Прорицатель
- Пророк
- Протыкатель
- Прут
- Прутик
- Разбойник
- Разведчик
- Разлом
- Разрушительный клинок
- Разрушительный молот
- Разум
- Раптор
- Раритет
- Раскол
- Рассвет
- Рассекатель
- Рассекающий удар
- Расщепитель
- Ритуал
- Рубец
- Рубитель
- Рывок
- Рыцарский шлем
- Рыцарь
- Саван
- Свет
- Сглаз
- Сегментный наплечник
- Скальпель
- Скальпорез
- Скандалист
- Скитальческий посох
- Скрывающий лицо шлем
- Сминатель
- Советник
- Соглашение
- Создатель трещин
- Сокол
- Сокрушительный удар
- Солдат
- Солнцеворот
- Соперник
- Союз
- Спектр
- Спутник
- Старейшина
- Старинный амулет
- Старшина
- Ствол
- Столб
- Страж
- Стрелоклад
- Строевой щит
- Стук
- Сувенир
- Судейский знак
- Судия
- Суровый взгляд
- Тавро
- Таинственный посох
- Таран
- Титан
- Тканевый покров
- Триумф
- Трофей
- Тул
- Туман
- Туманный покров
- Турнир
- Убийца
- Убор
- Удар
- Ужас
- Узел
- Укус
- Умудряющий жезл
- Умудряющий посох
- Уничтожение
- Фасад
- Фетиш
- Фигляр
- Флер
- Фонарь
- Хищник
- Хлыст
- Хозяин
- Хохлатый шлем
- Хранитель
- Хребет
- Центурион
- Чародейский жезл
- Часовой
- Частокол
- Черный жезл
- Чудотворный жезл
- Шаман
- Шепот
- Шило
- Шип
- Широкий нож
- Шлем-маска
- Шлепок
- Шрам
- Штандарт
- Щедрый дар
- Эрудит
- Ястреб
verbs:
- Зарождения
- Зарослей
- Захоронения
- Защитника
- Защиты
- Звезд
- Зверолова
- Зверства
- Зверя
- Зимы
- Злобы
- Змеи
- Знака
- Знамения
- Знания
- Зова
- Золы
- Зубов
- Идеала
- Идола
- Избавителя
- Избавления
- Избивания
- Изгнания
- Издевки
- Излечения
- Измельчения
- Иллюзии
- Инстинкта
- Инфекции
- Искры
- Искупления
- Искушения
- Исполина
- Исполнения
- Испорченности
- Испуга
- Испытания
- Истока
- Истоков
- Истязаний
- Исцеления
- Йети
- Капкана
- Караульного
- Кладезя
- Клеветы
- Клейма
- Клыка
- Клятвы
- Коварства
- Ковки
- Когорты
- Колдовского взрыва
- Колокольного звона
- Конклава
- Корней
- Короля
- Коряги
- Кочевника
- Кошмара
- Крапивы
- Кремации
- Кремня
- Крепости
- Креста
- Крика
- Кристаллизации
- Кровавой расправы
- Крови
- Крови богов
- Кровопролития
- Круговорота
- Крушителя
- Лазейки
- Левитации
- Легкого ветра
- Летальности
- Ливня
- Лозы
- Мангуста
- Мастерства
- Меры
- Милости
- Могилы
- Молниеносной волны
- Мора
- Мороза
- Морока
- Мощи
- Наваждения
- Награды
- Надежды
- Налета
- Нападения
- Напасти
- Напора
- Напряжения
- Насмешки
- Невинного
- Недовольства
- Недруга
- Недуга
- Неистовства
- Ненависти
- Неприязни
- Несчастий
- Неустойчивости
- Обета
- Обещания
- Обители
- Облаков
- Облегчения
- Обледенения
- Обморожения
- Ограды
- Одобрения
- Озлобленности
- Окалины
- Окончания
- Оконченности
- Окружения
- Омерзения
- Опасности
- Оплота
- Опоры
- Оправдания
- Опустошения
- Опустошённости
- Орудия
- Оружия
- Осквернителя
- Оскорбления
- Осмысленности
- Основ
- Основательности
- Основы
- Останков
- Острия
- Отваги
- Отвлечения
- Отвращения
- Отдохновения
- Отдыха
- Отрицания
- Отрога
- Отступника
- Охранения
- Падения
- Пакта
- Палача
- Памяти
- Паники
- Парапета
- Пекла
- Пепла
- Перебежки
- Переговоров
- Перелива
- Переполоха
- Пилигрима
- Пирата
- Пиршества
- Плана
- Плача
- Пленения
- Плети
- Плоти
- Побега
- Победителя
- Побоища
- Повеления
- Повелителя бури
- Погони
- Погребального костра
- Погребения
- Погружения
- Подготовки
- Поддержки
- Поджигателя
- Пожара
- Пожертвования
- Пожирателя
- Позора
- Поисков
- Покаяния
- Покорения
- Покоя
- Покровительства
- Полномочий
- Полога
- Порождения
- Порока
- Поручительства
- Порыва
- Порядка
- Посвящения
- Последнего средства
- Посредника
- Потока
- Потрясения
- Права
- Практики
- Праха
- Преграды
- Предвестника
- Преломления
- Преодоления
- Преследования
- Преследователя
- Преступления
- Приема
- Призмы
- Признания
- Приисков
- Прилива
- Пристанища
- Притока
- Притязания
- Приюта
- Провинции
- Продвижения
- Прозрения
- Происхождения
- Противоядия
- Проходимца
- Прохожего
- Процветания
- Прочности
- Путаницы
- Путешествия
- Пути
- Равновесия
- Разбоя
- Раздраженности
- Разногласия
- Разносчика заразы
- Разорителя
- Разрушителя
- Разряда
- Разума
- Ранения
- Раскаяния
- Рассвета
- Рвения
- Резервуара
- Резни
- Резца
- Реки
- Реликвии
- Роста
- Ростка
- Рубца
- Рыка
- Самообладания
- Святилища
- Семени
- Серы
- Силы
- Символа
- Сияния
- Скитальца
- Скорости
- Следопыта
- Слияния
- Слова
- Смелости
- Смерча
- Снегопада
- Снежной бури
- Согласия
- Содрогания
- Соединения
- Созерцателя
- Сокровищ
- Сокрушения
- Солнца
- Солнцестояния
- Соперничества
- Сопровождения
- Сосуда
- Союза
- Спазмов
- Спасения
- Спасителя
- Спектра
- Спокойствия
- Справедливости
- Срыва
- Ссылки
- Стенаний
- Стены
- Сопротивления
- Стиля
- Стойкости
- Столкновения
- Страдания
- Стража
- Стражника
- Странника
- Странствий
- Стратега
- Стратегии
- Судьбы
- Сути
- Тайны
- Таланта
- Творения
- Терзания
- Территории
- Тирана
- Топи
- Торнадо
- Трепета
- Триумфа
- Трофеев
- Тумана
- Тундры
- Убежища
- Удара
- Указа
- Укола
- Укрепления
- Укрытия
- Укуса
- Уловки
- Улья
- Упокоения
- Упразднения
- Упреждения
- Упрека
- Упреков
- Урока
- Усердия
- Успокоения
- Устройства
- Утешения
- Ушиба
- Формы
- Хаоса
- Хватки
- Хитрости
- Хладнокровия
- Хода
- Хранителя
- Хребта
- Цветения
- Цели
- Целомудрия
- Чудовища
- Чумы
- Шалости
- Шанса
- Шипа
- Шипов
- Шквала
- Шока
- Шрама
- Шторма
- Щедрости
- Ядовитых испарений
- Ядра
- Языков пламени
- Якоря
- Ярости
- Ясности
verb-ers (noun):
- Дубовый
- Алмазный
- Железный
- Золотой
- Серебрянный
- Деревянный
- Каменный
- Изумрудный
- Лавовый
- Водный
- Иссушенный
- Гранитный
- Кольчужный
- Керамический
- Еловый
- Берёзовый
- Джунглевый
- Акациевый
- Тёмно-дубовый
- Исступленный
- Истинный
- Исторический
- Истребляющий
- Кавалерийский
- Казнящий
- Калечащий
- Каменистый
- Каннибальский
- Караульный
- Качающийся
- Кипучий
- Клепанный
- Клерикальный
- Колдовской
- Колкий
- Колоссальный
- Колючий
- Колющий
- Королевский
- Корыстный
- Костяной
- Кочевнический
- Кошачий
- Кракенов
- Кратерный
- Крепкий
- Кризисный
- Кристальный
- Кровопийственный
- Кровопролитный
- Кровопускательный
- Курастский
- Курьерский
- Лазарев
- Леденящий
- Ледяной
- Лекарственный
- Лепрозный
- Лесной
- Летящий
- Лечебный
- Ливневый
- Лисий
- Лихорадочный
- Лишающий воздуха
- Лишающий разума
- Ловкий
- Ловчий
- Лунатичный
- Лучистый
- Магистрский
- Магический
- Магический кровавый
- Малахитовый
- Маниакальный
- Мародерский
- Маршевый
- Массивный
- Мастерский
- Материальный
- Медвежий
- Медный
- Мерзопакостный
- Мертвоземный
- Мерцающий
- Меткий
- Мирмидонов
- Мировой
- Мистический
- Могущественный
- Молниеносный
- Монархический
- Монарший
- Монструозный
- Морозный
- Мощный
- Мусорный
- Мучающий
- Мучительный
- Мыслительный
- Мятежный
- Наводящий страх
- Надежный
- Надзирательский
- Надменный
- Напористый
- Наставнический
- Настигающий
- Не имеющий равных
- Небесный
- Невыделанный
- Недобрый
- Неземной
- Незначительный
- Неистовый
- Некромантский
- Немилосердный
- Ненавистный
- Необычный
- Неодолимый
- Неповинующийся
- Неподатливый
- Непокидающий
- Непоколебимый
- Непреклонный
- Неприкосновенный
- Неприятный
- Непроницаемый
- Непрощающий
- Нерушимый
- Неснашиваемый
- Неукротимый
- Неумирающий
- Неумолимый
- Неустрашимый
- Неусыпный
- Нокаутирующий
- Нордовый
- Носорожий
- Ночной
- Нутряной
- Обжигающий
- Обожженный
- Обозленный
- Оборонительный
- Обособленный
- Обсидиановый
- Огневой
- Огненный
- Одеревеневший
- Одержимый
- Одинокий
- Ожесточающий
- Озаренный светом
- Озаряющий
- Омерзительный
- Омолаживающий
- Ониксовый
- Опаляющий
- Опасный
- Опережающий
- Опытный
- Опьяняющий
- Осадный
- Освященный
- Основательный
- Осторожный
- Остроконечный
- Острый
- Осушающий
- Отваживающий
- Отвердевший
- Отводящий
- Отклоняющий
- Отравляющий
- Отражательный
- Отражающий
- Отрекающийся
- Отталкивающий
- Отчаянный
- Отшельнический
- Охотничий
- Охранный
- Очищающий
- Ошарашивающий
- Памятный
- Парный
- Первобытный
- Первозданный
- Переводящий
- Перестрелочный
- Питающий
- Пламенеющий
- Пламенный
- Плотный
- Плотский
- Повышающий мастерство
- Повышающий проницательность
- Повышающий эрудицию
- Поглощающий
- Погружающий в раздумья
- Поддерживающий
- Поднебесный
- Поднимающий
- Подобающий
- Подпирающий
- Пожинающий
- Покрытый царапинами
- Покрытый чешуей
- Ползучий
- Полночный
- Полый
- Полярный
- Понижающий
- Поражающий
- Поражающий молнией
- Поспешный
- Потоковый
- Почитаемый
- Праведный
- Правосудный
- Правящий
- Превосходный
- Преданный
- Предательский
- Предводительский
- Преломляющий
- Преторианский
- Приводящий к помешательству
- Придающий бледность
- Призматический
- Примитивный
- Принадлежавший гуру
- Приносящий удачу
- Притягивающий
- Прицельный
- Причиняющий боль
- Причиняющий страдания
- Пробивающий
- Пробивной
- Пробуждающий
- Прогулочный
- Прозекторский
- Проказливый
- Проклятый
- Пронзающий
- Пронизывающий
- Прорицательский
- Пророческий
- Противоречивый
- Прохладный
- Прочный
- Прыжковый
- Пустырный
- Разбитый
- Разведывательный
- Раздрабливающий
- Раздражающий
- Разжигающий войну
- Разлагающий
- Разрушающий
- Разрушенный
- Разрывающий
- Разъедающий
- Разъяряющий
- Реанимирующий
- Редчайший
- Режущий
- Роковой
- Рыцарский
- Рыщущий
- Рьяный
- Саботирующий
- Самоотверженный
- Сангвинический
- Сбалансированный
- Сверхстойкий
- Светоносный
- Светящийся
- Свято чтимый
- Святой
- Сглаз
- Сгущающий кровь
- Северный
- Сердечный
- Серебряный
- Сержантский
- Сжигающий
- Сжигающий дотла
- Сжирающий
- Сианьсайский
- Сильный
- Сияющий
- Скальный
- Скитальческий
- Скитающийся
- Скорбный
- Скоростной
- Скороходный
- Скорпионий
- Скрепленный
- Скрепленный печатью
- Скрупулезный
- Скрывающийся
- Славный
- Следящий
- Слепящий
- Сливающийся с тьмой
- Смертельный
- Смертоносный
- Смещающий
- Совершенный
- Сознательный
- Сокрушающий
- Солдатский
- Сотрясающий
- Сочащийся
- Спасительный
- Спектральный
- Спиральный
- Старательский
- Стенающий
- Стигийский
- Стойкий
- Странный
- Страшный
- Строгий
- Студеный
- Стяжательский
- Суматошный
- Суровый
- Существенный
- Сущностный
- Таинственный
- Таинственный посох
- Твердокаменный
- Текучий
- Темный
- Теневой
- Терзающий
- Тихий
- Тлеющий
- Токсичный
- Толкающий
- Толковый
- Торговый
- Торжественный
- Точный
- Травмирующий
- Травящий
- Треснутый
- Трупный
- Тусклый
- Тяжелый
- Убийственный
- Убыстряющий
- Уверенный
- Увечащий
- Угрожающий
- Ударяющий
- Удушающий
- Ужасающий
- Ужасный
- Уклончивый
- Укрепленный
- Укрепляющий
- Укрывающий
- Умерщвляющий
- Умножающий
- Уничтожающий
- Упругий
- Уродующий
- Усиленный
- Усиливающий дух
- Ускоряющий
- Успокаивающий
- Устрашающий
- Утепляющий
- Ученический
- Учительский
- Ущербный
- Фаланговый
- Фантомный
- Фатальный
- Фобический
- Хитрый
- Хищный
- Холодный
- Холодящий
- Храбрый
- Чародейский
- Чернокнижный
- Черный
- Чертополоховый
- Чистый
- Чудный
- Шаманский
- Шипастый
- Шокирующий
- Штормовой
- Шулерский
- Шумный
- Эбеновый
- Экзекуционный
- Энергетический
- Энигматичный
- Эсквайрский
- Ядовитый
- Яростный
validMaterials:
  DIAMOND_HELMET: true
  DIAMOND_CHESTPLATE: true
  DIAMOND_LEGGINGS: true
  DIAMOND_BOOTS: true
  DIAMOND_SWORD: true
  DIAMOND_AXE: true
  DIAMOND_HOE: true
  DIAMOND_PICKAXE: true
  DIAMOND_SHOVEL: true
  IRON_HELMET: true
  IRON_CHESTPLATE: true
  IRON_LEGGINGS: true
  IRON_BOOTS: true
  IRON_SWORD: true
  IRON_AXE: true
  IRON_HOE: true
  IRON_PICKAXE: true
  IRON_SHOVEL: true
  GOLDEN_HELMET: true
  GOLDEN_CHESTPLATE: true
  GOLDEN_LEGGINGS: true
  GOLDEN_BOOTS: true
  GOLDEN_SWORD: true
  GOLDEN_AXE: true
  GOLDEN_HOE: true
  GOLDEN_PICKAXE: true
  GOLDEN_SHOVEL: true
  CHAINMAIL_HELMET: true
  CHAINMAIL_CHESTPLATE: true
  CHAINMAIL_LEGGINGS: true
  CHAINMAIL_BOOTS: true
  LEATHER_HELMET: true
  LEATHER_CHESTPLATE: true
  LEATHER_LEGGINGS: true
  LEATHER_BOOTS: true
  STONE_SWORD: true
  STONE_AXE: true
  STONE_HOE: true
  STONE_PICKAXE: true
  STONE_SHOVEL: true
  WOODEN_SWORD: true
  WOODEN_AXE: true
  WOODEN_HOE: true
  WOODEN_PICKAXE: true
  SHIELD: true
  SHEARS: true
  TURTLE_HELMET: true
  TRIDENT: true
  FISHING_ROD: true
  BOW: true
materialNames:
  swordName: Меч
  bowName: Лук
  pickaxe: Кирка
  spade: Лопата
  hoe: Мотыга
  axe: Топор
  helmet: Шлем
  chestplate: Броня
  leggings: Штаны
  boots: Ботинки
  shears: Ножницы
  fishingRod: Удочка
  shield: Щит
  trident: Трезубец
